on:
  milestone:
    types: [created, opened, edited]

jobs:
  spring-releasetrain-checks:    
    name: Check DueOn is on a Release Date
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        DUE_ON: ${{ github.event.milestone.due_on }}
      run: |
        wget https://repo.spring.io/plugins-snapshot/io/spring/releasetrain/spring-release-train-tools/1.0.0-SNAPSHOT/spring-release-train-tools-1.0.0-SNAPSHOT.jar
        java -cp spring-release-train-tools-1.0.0-SNAPSHOT.jar io.spring.releasetrain.CheckMilestoneDueOnMain --dueOn "$DUE_ON" --expectedDayOfWeek MONDAY --expectedMondayCount 3
