on:
  milestone:
    types: [created, opened, edited]

jobs:
  spring-releasetrain-checks:    
    name: Check DueOn is on a Release Date
    env:
      DUE_ON: ${{ github.event.milestone.due_on }}
    if: env.DUE_ON != ''
    runs-on: ubuntu-latest
    steps:
    - name: Validate DueOn
      run: |
        export TOOL_VERSION=0.1.1
        wget "https://repo.maven.apache.org/maven2/io/spring/releasetrain/spring-release-train-tools/$TOOL_VERSION/spring-release-train-tools-$TOOL_VERSION.jar"
        java -cp "spring-release-train-tools-$TOOL_VERSION.jar" io.spring.releasetrain.CheckMilestoneDueOnMain --dueOn "$DUE_ON" --expectedDayOfWeek MONDAY --expectedMondayCount 3
